Модуль 3: Задачи 1 и 2 - Добавлены решения
js-tasks-ru/jsbasic-20201214_fa1con pull request #5
Opened 2021-01-04 11:45 UTC by evgeniyZiganshin

Добавлены решения для задач 1 и 2 из модуля 3.

2021-01-04 11:55 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-04 17:57 UTC, SinimaWath requested changes

2021-01-04 17:57 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map(item => item.name);
Давай тут применим, деструкторизацию

2021-01-07 14:04 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Фильтрация по диапазону
+ должна фильтровать диапазон
+ не должна менять исходный массив
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать 'list-style-image' 
+ должна оставить пустую строку без изменений 
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'background-color'
```
```diff
Функция showSalary(users, age)
+ для пользователей до 40 лет должна вывести строку с зарплатами
+ для пользователей до 30 лет должна вывести строку с зарплатами
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-07 17:15 UTC, SinimaWath requested changes

2021-01-07 17:15 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  });
1. Давай стрелочную функцию
2. Давай через тернарный оператор

2021-01-07 17:15 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return joinSplitted;
НЕ стоит создавать временную переменную, когда можно сразу вернуть значение: return upper.join('')'

2021-01-07 17:15 UTC, SinimaWath commented on 3-module/4-task/index.js
> +
Давай через тернарный оператор: ... ? ... : ...

2021-01-07 17:15 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return filterShowSalary.join('\n');
Тут тоже не стоит делать временную переменную

2021-01-07 17:15 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return objMinMax;
Тоже не стоит делать временные переменные, а можно сразу возвращать обьект: return {....}

2021-01-07 17:16 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  const transformGetMinMax = str.split(/[,\s]+/)
Регулярные выражения нужно выносить в отдельные переменные(пре компилировать). 

`const TRANSFORM_RE = ....`;

2021-01-08 05:46 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```
```diff
Функция showSalary(users, age)
+ для пользователей до 40 лет должна вывести строку с зарплатами
+ для пользователей до 30 лет ��олжна вывести строку с зарплатами
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать 'background-color'
+ должна оставить пустую строку без изменений 
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'list-style-image' 
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-08 18:02 UTC, SinimaWath approved these changes

2021-01-08 18:02 UTC, merged