Модуль 4: Добавил решения заданий 1-3
js-tasks-ru/jsbasic-20201214_fa1con pull request #6
Opened 2021-01-09 10:47 UTC by evgeniyZiganshin

Модуль 4: Добавил решения для заданий 1,2,3.

2021-01-09 10:55 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2021-01-10 07:14 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку первой строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку пятой строки в красный
```
```diff
Функция makeFriendsList(friends)
+ проверяем содержимое списка
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ функция должна возвращать HTML список
```
```diff
Функция highlight
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-11 09:17 UTC, SinimaWath requested changes

2021-01-11 09:17 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  for (let name of friends) {
Давай forEach, так будет компактней

2021-01-11 09:17 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    li.textContent = `${name.firstName} ${name.lastName}`;
Создание под элемента(компонента), стоит лучше выделить в отдельную функцию: `createFriendLi(friend)`, чтобы можно было переиспользовать

2021-01-11 09:17 UTC, SinimaWath commented on 4-module/2-task/index.js
> +
Давай переделаем на forEach ;)

2021-01-11 09:17 UTC, SinimaWath commented on 4-module/3-task/index.js
> +        if (tr[i].cells[3].getAttribute('data-available') == "true") {
Немного непонятно по коду, откуда взялся index `3`, `2`, `1`. Их лучше стоит именновать переменной

2021-01-16 10:22 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку первой строки в красный
```
```diff
Функция makeFriendsList(friends)
+ функция должна возвращать HTML список
+ проверяем содержимое списка
+ Число элементов в списке и число объекто�� в массиве должны быть одинаковыми
```
```diff
Функция highlight
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-16 16:09 UTC, SinimaWath approved these changes

2021-01-16 16:09 UTC, merged